# Generated by Django 3.2.7 on 2021-10-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageauth', '0007_auto_20211019_1725'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='manageauth_studentprofile_unique',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
