# Generated by Django 3.2.7 on 2021-10-26 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageauth', '0008_auto_20211019_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='')),
                ('subjectID', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='manageauth.subject')),
                ('userID', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
