# Generated by Django 3.2.7 on 2021-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageauth', '0009_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fileName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
