# Generated by Django 2.2 on 2021-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageauth', '0011_auto_20211027_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile',
            field=models.IntegerField(default=True),
        ),
    ]
