# Generated by Django 3.2.7 on 2021-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageauth', '0014_auto_20211103_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='passwordStatus',
            field=models.CharField(default='unset', max_length=20, null=True),
        ),
    ]
