# Generated by Django 3.2.7 on 2021-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageauth', '0015_alter_studentprofile_passwordstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='passwordStatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
