# Generated by Django 2.2 on 2021-11-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageauth', '0016_alter_studentprofile_passwordstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='isApproved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
