# Generated by Django 3.2.7 on 2021-11-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageauth', '0018_auto_20211116_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='isRejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
