# Generated by Django 3.2.7 on 2021-11-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageauth', '0019_fileupload_isrejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
